import { Inter } from 'next/font/google'
import './globals.css'
import CustomNavbar from '@/components/CustomNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Work Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomNavbar/>
        <div className='flex justify-around'>
        <div>Left side Bar</div>
        <div>{children}</div>
        </div>
        <h3>This is the footer</h3>
      </body>
    </html>
  )
}
