import { Inter } from 'next/font/google'
import './globals.css'
import CustomNavbar from '@/components/CustomNavbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Work Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomNavbar/>
        {/* <div className='flex justify-around'> */}
        {/* <div>Left side Bar</div> */}
        <div className='mt-5 mb-5'>{children}</div>
        {/* </div> */}
        <Footer/>
      </body>
    </html>
  )
}
